name: Quality Control for Python code
on: [push]
jobs:
  Quality-Control-Python-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Prepare Python environnement
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
      - name: Run Ruff (format) on Python code
        run: |
          ruff format --diff ${{ github.workspace }}/scripts/*.py
      - name: Run Ruff (check) on Python code
        run: |
          ruff check --diff ${{ github.workspace }}/scripts/*.py
